== Appropriating the Reformation

=== Top Down Or Bottom Up?

There are two basic ways in which changes could occur: either from a lot of popular support that then forces the leadership to adopt the change, or from the leaders imposing the changes on the people

While the exact process varied from area to area, it was usually a balance of the two forces happening at the same time; the leadership would generally be both excited and fearful about the changes, as would the people

=== Top Down For the Reformation

Typically it was the leaders -- or those that held considerable influence on them -- that were the Humanists and the like, and therefore more likely to agree with the Reformer's methods and ideas

Also, they were often sick of the power that Rome held over them and saw it as an opportunity to release those shackles

=== Top Down Against the Reformation

They resisted the changes because those changes often caused conflict and disorder, which are anathema to politicians (The fundamental purpose of government, after all, is to ensure the public peace)

Besides, if people started questioning the authority of Rome, what **_other_** authorities might they start questioning?

=== Bottom Up For the Reformation

The people were excited because they saw the Reformers as actually trying to teach them Christianity instead of simply telling them "`Thou shall`" do this and "`Thou shall not`" do that with a long list of rules

They also were overjoyed to be released from the yoke of the laws that the Reformers said were contrary to the Gospel

=== Bottom Up Against the Reformation

They feared the changes, though, because it was new, alien, and disrupted the life they knew

Most people, then as now, just want to raise their families in peace

Remember, this was not a "`tolerant`" time in history: Being different in any way -- much less openly going against the established order -- was often met with torture and the death of you and those you love

=== Tipping Point

Throwing doctrine back into the fray, many people (leaders and led alike) fought the changes because they felt that Catholic doctrine was Godly and the Reformers were heretics

Of course the same happened in reverse

Whether an individual supported or fought the Reformation, and how much he did so, depended on a combination of all of the above factors

=== Demographics

There is no way to be able to say, "`Because this person was in this demographic, he must have been Protestant/Catholic,`" as we discussed before

However, when reforms did occur it was because of "`middle class`" agitation (Artisans, shop keepers, petty officials, etc.)

=== Middle Class Reformation

They often had a mixture of the pressures and concerns of both the leadership and the populace, and with influence in both arenas.

They generally had enough power to stop or enforce edicts from above, and help or hinder pressure from below.

So when the "`middling classes`" had gained sufficient support within its ranks to call for reform, it generally got its way.

=== Building Critical Mass

This process, even when in full motion, could take some time (remember many of the delays that even Zwingli encountered in Zurich).

Usually, though, it happened as a series of stages of small agitations and concessions until critical mass was achieved.
