== Shifting Sands in England

=== Religious Leadship

England serves as a prime example of the dramatic ways how the country's ruler not only affects the religious climate of the nation, but how insane the conditions could get as the direction of that leadership changes

=== Edward VI Comes To the Throne

After the death of Henry VIII, Prince Edward (son of Henry's third wife, Jane Seymour) became King Edward VI at the age of nine years old

His uncle, Edward Seymour, was named Lord Protector and Duke of Somerset, acting as young Edward's ward until he was of age to fully assume power

=== Start of the Edwardian Reformation

Under Edward Seymour, some of the anti-Protestant laws were repealed, the laity was allowed to drink the blood in the Eucharist, priests were allowed to marry, and some other rather moderate reforms were instituted in a piecemeal way

[.small]
It's Thomas Crammer, the Archbishop of Canterbury from Henry's reign, who actually carried them out

Edward Seymour was quickly removed from power and replaced by John Dudley, the Duke of Northumberland

=== Edwardian Reformation Part 2

He was far more radical than his predecessor, such as:

* Church and priestly vestments were dramatically simplified

* The partition was moved to be behind the worshipers: the symbolism was no longer a separation between the worshipers and the priest & the Elements, but rather between the worshipers and the world

* People were to now use a Communion Table instead of the coming to the alter

Dudley also brings in a lot of very Protestant doctrines into the English Church

=== A Refuge In the Storm

During Edward's reign, England functioned as a kind of "`second Geneva,`" taking in religious refugees

Based on some of the new ideas being imported from the refugees, it is during this time that the English Book of Common Prayer is written

=== The Edwardian Reformation Ends

However, just as England was starting to inch toward becoming Protestant, Edward VI died at the age of 16, in 1553. (He had always been a sickly boy)

=== Mary Takes the Throne

That meant that the country was given to his half-sister, Mary Tudor

[.small]
Henry had three living children by his three wives (Mary's older brother died a few weeks after he was born, and there were others by all of the wives that didn't make it to birth), and all three of them would eventually take the throne.

=== Atoning for England's Infidelity

Mary's first order of business was to undo the heresies of her brother and reunite England with Mother Rome

She recalled Reginald Paul from Italy (who had left England under Protestant rule) and made him the Archbishop of Canterbury. (It was then Crammer who was exiled)

She reinstates the mass, declares England to be Catholic again, and asks for -- and receives -- Rome's forgiveness for England's infidelity

=== England Coming Home

At first, this was a popular move on her part: England had always been Catholic, and some official edicts over the course of a few years weren't going to change people's core beliefs

England had finally come back "`home`"

=== Overzealous Return

In her passion for Catholicism, though, she eventually led to its downfall in England

=== Uniting With the Catholic Empire

Her first seriously unpopular move was to marry Charles V's son, Philip II

The marriage created a strong tie with not only with Spain, but with the Empire

Spain was a Catholic nation, so she had therefore allied herself with a strongly Catholic country to aid in any problems she might have with Protestants

=== Undoing the Damage to Her Mother's Name

And finally, she was the daughter of Katherine of Aragon -- a Spanish house whose name had been dragged through the mud when Henry VIII tried to get the annulment.

If an English-Spanish union was good and proper then, then it was good and proper now

=== English Nationalism

Unfortunately for Mary, a lot had happened during those years -- including a growing sense of xenophobia

During the attempts to justify annulling the marriage with Katherine in favor of Anne, a lot of appeals to English nationalism were made

Since the downfall of Katherine, the English had quite gotten used to the idea of not having their monarch "`unduly influenced`" by a foreign power

There were now doubts about where Mary's loyalties would lie

=== Bloody Mary

The second thing she did that was popular at first but became the biggest blot on her legacy is what has given her the name that she is most remembered for today: Bloody Mary

Over the course of about three and a half years, she ordered the inquisitions and executions of nearly 300 Protestants

=== English Martyrs

Protestants would grab onto these things and make extremely efficient use of them, drawing the equation in English minds of:

* Roman Catholicism = Spanish Imperialism
* Persecution & Cruelty

=== Encouraging Radicalism

The persecution drove many people out of England and into the continent

As was the case with the same thing happening with France, this meant that they got hardcore indoctrination in much more "`pure`" Protestant doctrines and practices

=== Elizabeth Takes the Throne

Mary I had been falsely pregnant twice (her body reacted as if it were pregnant, but there was no child); the second time was due to uterine cancer

When Elizabeth then become queen and make England Protestant again (and manage to stay in power long enough to make it "`stick`"), these exiles would bring back with them far more radical views than they would have had otherwise

=== Religious Schizophrenia

So, to help get a real feel for the kind of religious schizophrenia people were subjected to, take a child born in 1520...

=== England's Official Religions

If he conformed to what his sovereign proclaimed, by the time he is 40 years old he would have practiced:

. Roman Catholicism
. Henrician Catholicism
. a moderate Edwardian Protestantism
. a more extreme Edwardian Protestantism
. a return to Catholicism
. Elizabethan Protestantism (roughly modern Anglicanism)

+++&nbsp;+++

[.small]
Of course if at any point he didn't conform he was subject to the torture, ruination and execution for himself and his entire family
