= Church History Worksheet
:stylesheet: worksheet.css

== The Philosopher -- Aristotle

What were some of the differences between Plato and Aristotle?

What was one of the direct benefits for Christ's Church of Aristotle's most famous student?

== Formal Logic

What are some of the things formal logic is especially good at?

What benefits did the incorperation of logic into Greek language and culture afford the New Testament writers?

== Matter, Form and Substance

What is the difference between the "`essence`" and the "`accidens`", and how do they relate to the "`substance`" of something?

What doctrines has this distinction been used to help explain?

== Causality

What is "`Teleology`"?

What is "`Christian Teleology`"?

== The Unmoved Mover (Romans 1:19-22)

Who/what is the "`Unmoved Mover`"? Why is it a "`logical necessity`"?

Why does God fit that description? Why does he not fit that description?

== The Rise of Islam

What century did Islam start? When was its "`Golden Age`"?

Who are "`The People of the Book`"? What's their relationship to Islam?

What are some of the fundimental differences between how Muhamed "`received`" the Quran and how the Biblical authors were "`inspired`"?

What was one of the major blessings God brought from the conflict with Islam?
