= Church History Worksheet
:stylesheet: worksheet.css

http://bit.ly/churchhist

== The Philosopher -- Aristotle

What were some of the differences between Plato and Aristotle?

What was one of the direct benefits for Christ's Church of Aristotle's most famous student?

== Formal Logic

What are some of the things formal logic is especially good at?

What benefits did the incorporation of logic into Greek language and culture afford the New Testament writers?

== Matter, Form and Substance

What is the difference between the "`essence`" and the "`accidens`", and how do they relate to the "`substance`" of something?

What doctrines has this distinction been used to help explain?

== Causality

What is "`Teleology`"?

What is "`Christian Teleology`"?

== The Unmoved Mover (Romans 1:19-22)

Who/what is the "`Unmoved Mover`"? Why is it a "`logical necessity`"?

Why does God fit that description? Why does he not fit that description?

== The Rise of Islam

What century did Islam start? When was its "`Golden Age`"?

Who are "`The People of the Book`"? What's their relationship to Islam?

What are some of the fundamental differences between how Mohamed "`received`" the Quran and how the Biblical authors were "`inspired`"?

What was one of the major blessings God brought from the conflict with Islam?

== The "`Doctor Angelicus`"

What are some of the things Thomas Aquinas most known for?

== True But Not True

What was/is "`double truth`"?

What are some modern examples of Christians commonly falling into that contradiction?

== Natural and Revealed Theology

Is it possible for Faith ("`special revelation`") the contradict Reason ("`general revelation`")?

What did Aquinas mean by "`mediated knowledge`"?

== The Existence of God

What strengths/weaknesses do the five "`proofs`" of God have?

== Aristotelian Scholasticism

What are some of the advantages/disadvantages to having an "`orthodoxy`" for universities?

== Disputation

What is the "`Disputation`"?

== Reflecting On God’s Wisdom

What could be more excellent and praiseworthy than God? What could be less praiseworthy than the fallen world?

How does modern science use deduction? Induction?

== Abusing the Unverifiable

How would the Scholastics argue for things that were impossible to verify? Has that gone away?

What is one of the most often used "`tool`" for such arguments?

== Allegory

Is the Bible a book of allegory?

How is allegory used in modern Christianity?

== Normative Thought

How are "`normative`" (prescriptive) ways of thinking about people a great thing? Why can it be a horrible thing?

== Violating God's Order

Can you give some major examples of "`synchronism`" that have become basic features of modern Christianity? (Some examples to think about: What are the two primary Christian holidays? Why is Mary effectively seen as a goddess even though she's not portrayed that way in the Bible?)

== Super-Natural

Why are we so quick to forget that we fight against "`the spiritual forces of evil in the heavenly realms`"?

Is the "`Materialist Magician`" a realistic threat?

== Witchcraft

What is "`witchcraft`"? Can there be a "`good witch`"?

What was the purpose of burning a witch?

== General Demographics Toward the End of the 15th Century

What were some of the primary population centers of Europe?

What did child mortality look like?

== The Black Death

What were some of the principle effects of the Plague?

Why was is so dangerous that people were starting to question their masters?

== Clergical Rights

Why were both the common people and lords resentful of the clergy?

== The Structure of the Medieval Church

What was so wonderful/terrible about the view of the Church being "`eternal`"?

What seperated clergy from laity? When would that get changed to be closer to what we recognize?

What was the general religious "`tone`" heading into the Renaissance and Reformation?

== Faith

Have you ever met people that profess believing what their church believes, but haven't really learned what that is?

Why was it reasonable for the clergy to not focus on educating their flocks on all the points of Christian doctrine?

== Heresy

Given the extreme importance of saving and protecting souls, are "`extreme`" measures called for?

Where do you draw the line? Where does the Bible draw the line?

== Renaissance Humanism

What was one of the core focusses of Renaissance? What were they trying to recover?

== Christianity That Is Practical

What are some of the advantages and disadvantages involved with "`practical`" Christianity?

How about for "`theoretical`" Christianity?

== Straying From Her Roots

Who was "`The Prince of the Humanists`" and what was one of his biggest contributions to the Church?
